// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/_supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.90.1";
function supabaseForUser(ctx) {
  const g = globalThis;
  const url = g.Deno?.env?.get?.("SUPABASE_URL") ?? g.process?.env?.SUPABASE_URL;
  const key = g.Deno?.env?.get?.("SUPABASE_PUBLISHABLE_KEY") ?? g.process?.env?.SUPABASE_PUBLISHABLE_KEY;
  return createClient(url, key, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/whoami.ts
var whoami_default = defineTool({
  name: "whoami",
  title: "Qui\xE9n soy",
  description: "Devuelve el usuario autenticado (id, email, tenant y roles).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const [{ data: profile }, { data: roles }] = await Promise.all([
      sb.from("profiles").select("user_id,email,nombre,apellido,tenant_id,sucursal_id,activo").eq("user_id", userId).maybeSingle(),
      sb.from("user_roles").select("role").eq("user_id", userId)
    ]);
    const payload = {
      user_id: userId,
      email: ctx.getUserEmail(),
      profile,
      roles: (roles ?? []).map((r) => r.role)
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-shipments.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var list_shipments_default = defineTool2({
  name: "list_shipments",
  title: "Listar env\xEDos",
  description: "Lista los env\xEDos del tenant del usuario, con filtros opcionales por estado, ciudad y rango de fechas.",
  inputSchema: {
    estado: z.string().optional().describe("Estado interno (ej: pendiente, en_reparto, entregado, cancelado)."),
    ciudad: z.string().optional().describe("Filtro por ciudad de entrega (coincidencia parcial)."),
    desde: z.string().optional().describe("Fecha ISO (creado desde)."),
    hasta: z.string().optional().describe("Fecha ISO (creado hasta)."),
    limit: z.number().int().min(1).max(100).default(25)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ estado, ciudad, desde, hasta, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    let q = sb.from("envios").select("id,tracking_number,tracking_externo,estado,destinatario_nombre,ciudad_entrega,direccion_entrega,precio_total,created_at").order("created_at", { ascending: false }).limit(limit);
    if (estado) q = q.eq("estado", estado);
    if (ciudad) q = q.ilike("ciudad_entrega", `%${ciudad}%`);
    if (desde) q = q.gte("created_at", desde);
    if (hasta) q = q.lte("created_at", hasta);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { shipments: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-shipment.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_shipment_default = defineTool3({
  name: "get_shipment",
  title: "Detalle de env\xEDo",
  description: "Busca un env\xEDo por tracking (interno o externo) y devuelve su detalle completo.",
  inputSchema: {
    tracking: z2.string().min(1).describe("tracking_number o tracking_externo.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ tracking }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("envios").select("*").or(`tracking_number.eq.${tracking},tracking_externo.eq.${tracking}`).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "No se encontr\xF3 el env\xEDo" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { shipment: data }
    };
  }
});

// src/lib/mcp/tools/shipment-stats.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
var shipment_stats_default = defineTool4({
  name: "shipment_stats",
  title: "Estad\xEDsticas de env\xEDos",
  description: "Conteos de env\xEDos por estado en un rango de fechas (por defecto \xFAltimos 30 d\xEDas).",
  inputSchema: {
    desde: z3.string().optional().describe("ISO date inicio"),
    hasta: z3.string().optional().describe("ISO date fin")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ desde, hasta }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const from = desde ?? new Date(Date.now() - 30 * 864e5).toISOString();
    const to = hasta ?? (/* @__PURE__ */ new Date()).toISOString();
    const estados = ["pendiente", "en_reparto", "entregado", "cancelado", "reprogramado", "en_sucursal"];
    const counts = {};
    await Promise.all(
      estados.map(async (e) => {
        const { count } = await sb.from("envios").select("id", { count: "exact", head: true }).eq("estado", e).gte("created_at", from).lte("created_at", to);
        counts[e] = count ?? 0;
      })
    );
    const total = Object.values(counts).reduce((a, b) => a + b, 0);
    const payload = { desde: from, hasta: to, total, counts };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "uhlgimnmfifmrxraorrl";
var mcp_default = defineMcp({
  name: "geologistick-mcp",
  title: "Geologistick MCP",
  version: "0.1.0",
  instructions: "Herramientas de Geologistick para asistentes de IA. Cada llamada se ejecuta como el usuario autenticado (respeta tenant y RLS). Us\xE1 `whoami` para verificar la conexi\xF3n, `list_shipments` y `get_shipment` para consultar env\xEDos, y `shipment_stats` para conteos por estado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_shipments_default, get_shipment_default, shipment_stats_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
