-- Delete existing permissions to insert fresh complete matrix
DELETE FROM public.role_permissions;

-- Insert ALL permissions for ALL roles with appropriate enabled status
-- This creates a complete matrix where Super Admin can toggle any permission

-- Define all system permissions for each role
-- SUPER_ADMIN - All enabled
INSERT INTO public.role_permissions (role, permission_key, permission_name, description, enabled) VALUES
('super_admin', 'dashboard.view', 'Ver Dashboard', 'Acceso al panel de control principal', true),
('super_admin', 'shipments.view', 'Ver Envíos', 'Consultar lista de envíos', true),
('super_admin', 'shipments.create', 'Crear Envíos', 'Registrar nuevos envíos', true),
('super_admin', 'shipments.edit', 'Editar Envíos', 'Modificar datos de envíos', true),
('super_admin', 'shipments.scan', 'Escanear QR', 'Escanear códigos QR de envíos', true),
('super_admin', 'tracking.view', 'Ver Tracking', 'Consultar estado de envíos públicamente', true),
('super_admin', 'routes.plan', 'Planificar Rutas', 'Usar el planificador de rutas', true),
('super_admin', 'route_sheets.view', 'Ver Hojas de Ruta', 'Consultar hojas de ruta', true),
('super_admin', 'route_sheets.create', 'Crear Hojas de Ruta', 'Generar nuevas hojas de ruta', true),
('super_admin', 'live_map.view', 'Ver Mapa en Vivo', 'Monitorear ubicación de choferes', true),
('super_admin', 'drivers.manage', 'Gestionar Choferes', 'Administrar choferes del sistema', true),
('super_admin', 'vehicles.manage', 'Gestionar Vehículos', 'Administrar flota de vehículos', true),
('super_admin', 'my_routes.view', 'Ver Mis Rutas', 'Ver rutas asignadas personalmente', true),
('super_admin', 'route.start', 'Iniciar Ruta', 'Comenzar una ruta de entrega', true),
('super_admin', 'navigation.active', 'Navegación Activa', 'Usar navegación GPS en ruta', true),
('super_admin', 'delivery.confirm', 'Confirmar Entregas', 'Registrar entregas con foto/firma', true),
('super_admin', 'incidents.report', 'Reportar Incidentes', 'Registrar problemas durante entrega', true),
('super_admin', 'cash.manage', 'Gestionar Caja', 'Manejar sesiones de caja', true),
('super_admin', 'settlements.driver.view', 'Ver Liquidaciones Chofer', 'Consultar liquidaciones de choferes', true),
('super_admin', 'settlements.driver.manage', 'Gestionar Liquidaciones Chofer', 'Aprobar/pagar liquidaciones de choferes', true),
('super_admin', 'settlements.branch.view', 'Ver Liquidaciones Sucursal', 'Consultar liquidaciones de sucursales', true),
('super_admin', 'settlements.branch.manage', 'Gestionar Liquidaciones Sucursal', 'Aprobar liquidaciones de sucursales', true),
('super_admin', 'settlements.client.view', 'Ver Liquidaciones Cliente', 'Consultar liquidaciones de clientes', true),
('super_admin', 'commissions.view', 'Ver Mis Comisiones', 'Consultar comisiones propias', true),
('super_admin', 'clients.view', 'Ver Clientes', 'Consultar lista de clientes', true),
('super_admin', 'clients.manage', 'Gestionar Clientes', 'Administrar clientes', true),
('super_admin', 'branches.manage', 'Gestionar Sucursales', 'Administrar sucursales', true),
('super_admin', 'rates.manage', 'Gestionar Tarifas', 'Configurar precios y tarifas', true),
('super_admin', 'users.manage', 'Gestionar Usuarios', 'Administrar usuarios del sistema', true),
('super_admin', 'roles.manage', 'Gestionar Roles', 'Configurar permisos por rol', true);

-- ADMIN - Almost all enabled except driver-specific
INSERT INTO public.role_permissions (role, permission_key, permission_name, description, enabled) VALUES
('admin', 'dashboard.view', 'Ver Dashboard', 'Acceso al panel de control principal', true),
('admin', 'shipments.view', 'Ver Envíos', 'Consultar lista de envíos', true),
('admin', 'shipments.create', 'Crear Envíos', 'Registrar nuevos envíos', true),
('admin', 'shipments.edit', 'Editar Envíos', 'Modificar datos de envíos', true),
('admin', 'shipments.scan', 'Escanear QR', 'Escanear códigos QR de envíos', true),
('admin', 'tracking.view', 'Ver Tracking', 'Consultar estado de envíos públicamente', true),
('admin', 'routes.plan', 'Planificar Rutas', 'Usar el planificador de rutas', true),
('admin', 'route_sheets.view', 'Ver Hojas de Ruta', 'Consultar hojas de ruta', true),
('admin', 'route_sheets.create', 'Crear Hojas de Ruta', 'Generar nuevas hojas de ruta', true),
('admin', 'live_map.view', 'Ver Mapa en Vivo', 'Monitorear ubicación de choferes', true),
('admin', 'drivers.manage', 'Gestionar Choferes', 'Administrar choferes del sistema', true),
('admin', 'vehicles.manage', 'Gestionar Vehículos', 'Administrar flota de vehículos', true),
('admin', 'my_routes.view', 'Ver Mis Rutas', 'Ver rutas asignadas personalmente', false),
('admin', 'route.start', 'Iniciar Ruta', 'Comenzar una ruta de entrega', false),
('admin', 'navigation.active', 'Navegación Activa', 'Usar navegación GPS en ruta', false),
('admin', 'delivery.confirm', 'Confirmar Entregas', 'Registrar entregas con foto/firma', false),
('admin', 'incidents.report', 'Reportar Incidentes', 'Registrar problemas durante entrega', false),
('admin', 'cash.manage', 'Gestionar Caja', 'Manejar sesiones de caja', true),
('admin', 'settlements.driver.view', 'Ver Liquidaciones Chofer', 'Consultar liquidaciones de choferes', true),
('admin', 'settlements.driver.manage', 'Gestionar Liquidaciones Chofer', 'Aprobar/pagar liquidaciones de choferes', true),
('admin', 'settlements.branch.view', 'Ver Liquidaciones Sucursal', 'Consultar liquidaciones de sucursales', true),
('admin', 'settlements.branch.manage', 'Gestionar Liquidaciones Sucursal', 'Aprobar liquidaciones de sucursales', true),
('admin', 'settlements.client.view', 'Ver Liquidaciones Cliente', 'Consultar liquidaciones de clientes', true),
('admin', 'commissions.view', 'Ver Mis Comisiones', 'Consultar comisiones propias', false),
('admin', 'clients.view', 'Ver Clientes', 'Consultar lista de clientes', true),
('admin', 'clients.manage', 'Gestionar Clientes', 'Administrar clientes', true),
('admin', 'branches.manage', 'Gestionar Sucursales', 'Administrar sucursales', true),
('admin', 'rates.manage', 'Gestionar Tarifas', 'Configurar precios y tarifas', true),
('admin', 'users.manage', 'Gestionar Usuarios', 'Administrar usuarios del sistema', true),
('admin', 'roles.manage', 'Gestionar Roles', 'Configurar permisos por rol', false);

-- SUPERVISOR
INSERT INTO public.role_permissions (role, permission_key, permission_name, description, enabled) VALUES
('supervisor', 'dashboard.view', 'Ver Dashboard', 'Acceso al panel de control principal', true),
('supervisor', 'shipments.view', 'Ver Envíos', 'Consultar lista de envíos', true),
('supervisor', 'shipments.create', 'Crear Envíos', 'Registrar nuevos envíos', true),
('supervisor', 'shipments.edit', 'Editar Envíos', 'Modificar datos de envíos', true),
('supervisor', 'shipments.scan', 'Escanear QR', 'Escanear códigos QR de envíos', true),
('supervisor', 'tracking.view', 'Ver Tracking', 'Consultar estado de envíos públicamente', true),
('supervisor', 'routes.plan', 'Planificar Rutas', 'Usar el planificador de rutas', true),
('supervisor', 'route_sheets.view', 'Ver Hojas de Ruta', 'Consultar hojas de ruta', true),
('supervisor', 'route_sheets.create', 'Crear Hojas de Ruta', 'Generar nuevas hojas de ruta', true),
('supervisor', 'live_map.view', 'Ver Mapa en Vivo', 'Monitorear ubicación de choferes', true),
('supervisor', 'drivers.manage', 'Gestionar Choferes', 'Administrar choferes del sistema', true),
('supervisor', 'vehicles.manage', 'Gestionar Vehículos', 'Administrar flota de vehículos', true),
('supervisor', 'my_routes.view', 'Ver Mis Rutas', 'Ver rutas asignadas personalmente', false),
('supervisor', 'route.start', 'Iniciar Ruta', 'Comenzar una ruta de entrega', false),
('supervisor', 'navigation.active', 'Navegación Activa', 'Usar navegación GPS en ruta', false),
('supervisor', 'delivery.confirm', 'Confirmar Entregas', 'Registrar entregas con foto/firma', false),
('supervisor', 'incidents.report', 'Reportar Incidentes', 'Registrar problemas durante entrega', false),
('supervisor', 'cash.manage', 'Gestionar Caja', 'Manejar sesiones de caja', true),
('supervisor', 'settlements.driver.view', 'Ver Liquidaciones Chofer', 'Consultar liquidaciones de choferes', true),
('supervisor', 'settlements.driver.manage', 'Gestionar Liquidaciones Chofer', 'Aprobar/pagar liquidaciones de choferes', true),
('supervisor', 'settlements.branch.view', 'Ver Liquidaciones Sucursal', 'Consultar liquidaciones de sucursales', true),
('supervisor', 'settlements.branch.manage', 'Gestionar Liquidaciones Sucursal', 'Aprobar liquidaciones de sucursales', true),
('supervisor', 'settlements.client.view', 'Ver Liquidaciones Cliente', 'Consultar liquidaciones de clientes', true),
('supervisor', 'commissions.view', 'Ver Mis Comisiones', 'Consultar comisiones propias', false),
('supervisor', 'clients.view', 'Ver Clientes', 'Consultar lista de clientes', true),
('supervisor', 'clients.manage', 'Gestionar Clientes', 'Administrar clientes', true),
('supervisor', 'branches.manage', 'Gestionar Sucursales', 'Administrar sucursales', false),
('supervisor', 'rates.manage', 'Gestionar Tarifas', 'Configurar precios y tarifas', false),
('supervisor', 'users.manage', 'Gestionar Usuarios', 'Administrar usuarios del sistema', false),
('supervisor', 'roles.manage', 'Gestionar Roles', 'Configurar permisos por rol', false);

-- OPERADOR
INSERT INTO public.role_permissions (role, permission_key, permission_name, description, enabled) VALUES
('operador', 'dashboard.view', 'Ver Dashboard', 'Acceso al panel de control principal', true),
('operador', 'shipments.view', 'Ver Envíos', 'Consultar lista de envíos', true),
('operador', 'shipments.create', 'Crear Envíos', 'Registrar nuevos envíos', true),
('operador', 'shipments.edit', 'Editar Envíos', 'Modificar datos de envíos', true),
('operador', 'shipments.scan', 'Escanear QR', 'Escanear códigos QR de envíos', true),
('operador', 'tracking.view', 'Ver Tracking', 'Consultar estado de envíos públicamente', true),
('operador', 'routes.plan', 'Planificar Rutas', 'Usar el planificador de rutas', true),
('operador', 'route_sheets.view', 'Ver Hojas de Ruta', 'Consultar hojas de ruta', true),
('operador', 'route_sheets.create', 'Crear Hojas de Ruta', 'Generar nuevas hojas de ruta', true),
('operador', 'live_map.view', 'Ver Mapa en Vivo', 'Monitorear ubicación de choferes', true),
('operador', 'drivers.manage', 'Gestionar Choferes', 'Administrar choferes del sistema', false),
('operador', 'vehicles.manage', 'Gestionar Vehículos', 'Administrar flota de vehículos', false),
('operador', 'my_routes.view', 'Ver Mis Rutas', 'Ver rutas asignadas personalmente', false),
('operador', 'route.start', 'Iniciar Ruta', 'Comenzar una ruta de entrega', false),
('operador', 'navigation.active', 'Navegación Activa', 'Usar navegación GPS en ruta', false),
('operador', 'delivery.confirm', 'Confirmar Entregas', 'Registrar entregas con foto/firma', false),
('operador', 'incidents.report', 'Reportar Incidentes', 'Registrar problemas durante entrega', false),
('operador', 'cash.manage', 'Gestionar Caja', 'Manejar sesiones de caja', true),
('operador', 'settlements.driver.view', 'Ver Liquidaciones Chofer', 'Consultar liquidaciones de choferes', false),
('operador', 'settlements.driver.manage', 'Gestionar Liquidaciones Chofer', 'Aprobar/pagar liquidaciones de choferes', false),
('operador', 'settlements.branch.view', 'Ver Liquidaciones Sucursal', 'Consultar liquidaciones de sucursales', false),
('operador', 'settlements.branch.manage', 'Gestionar Liquidaciones Sucursal', 'Aprobar liquidaciones de sucursales', false),
('operador', 'settlements.client.view', 'Ver Liquidaciones Cliente', 'Consultar liquidaciones de clientes', false),
('operador', 'commissions.view', 'Ver Mis Comisiones', 'Consultar comisiones propias', false),
('operador', 'clients.view', 'Ver Clientes', 'Consultar lista de clientes', true),
('operador', 'clients.manage', 'Gestionar Clientes', 'Administrar clientes', false),
('operador', 'branches.manage', 'Gestionar Sucursales', 'Administrar sucursales', false),
('operador', 'rates.manage', 'Gestionar Tarifas', 'Configurar precios y tarifas', false),
('operador', 'users.manage', 'Gestionar Usuarios', 'Administrar usuarios del sistema', false),
('operador', 'roles.manage', 'Gestionar Roles', 'Configurar permisos por rol', false);

-- CHOFER - Driver specific permissions enabled
INSERT INTO public.role_permissions (role, permission_key, permission_name, description, enabled) VALUES
('chofer', 'dashboard.view', 'Ver Dashboard', 'Acceso al panel de control principal', false),
('chofer', 'shipments.view', 'Ver Envíos', 'Consultar lista de envíos', false),
('chofer', 'shipments.create', 'Crear Envíos', 'Registrar nuevos envíos', false),
('chofer', 'shipments.edit', 'Editar Envíos', 'Modificar datos de envíos', false),
('chofer', 'shipments.scan', 'Escanear QR', 'Escanear códigos QR de envíos', true),
('chofer', 'tracking.view', 'Ver Tracking', 'Consultar estado de envíos públicamente', true),
('chofer', 'routes.plan', 'Planificar Rutas', 'Usar el planificador de rutas', false),
('chofer', 'route_sheets.view', 'Ver Hojas de Ruta', 'Consultar hojas de ruta', true),
('chofer', 'route_sheets.create', 'Crear Hojas de Ruta', 'Generar nuevas hojas de ruta', false),
('chofer', 'live_map.view', 'Ver Mapa en Vivo', 'Monitorear ubicación de choferes', false),
('chofer', 'drivers.manage', 'Gestionar Choferes', 'Administrar choferes del sistema', false),
('chofer', 'vehicles.manage', 'Gestionar Vehículos', 'Administrar flota de vehículos', false),
('chofer', 'my_routes.view', 'Ver Mis Rutas', 'Ver rutas asignadas personalmente', true),
('chofer', 'route.start', 'Iniciar Ruta', 'Comenzar una ruta de entrega', true),
('chofer', 'navigation.active', 'Navegación Activa', 'Usar navegación GPS en ruta', true),
('chofer', 'delivery.confirm', 'Confirmar Entregas', 'Registrar entregas con foto/firma', true),
('chofer', 'incidents.report', 'Reportar Incidentes', 'Registrar problemas durante entrega', true),
('chofer', 'cash.manage', 'Gestionar Caja', 'Manejar sesiones de caja', false),
('chofer', 'settlements.driver.view', 'Ver Liquidaciones Chofer', 'Consultar liquidaciones de choferes', false),
('chofer', 'settlements.driver.manage', 'Gestionar Liquidaciones Chofer', 'Aprobar/pagar liquidaciones de choferes', false),
('chofer', 'settlements.branch.view', 'Ver Liquidaciones Sucursal', 'Consultar liquidaciones de sucursales', false),
('chofer', 'settlements.branch.manage', 'Gestionar Liquidaciones Sucursal', 'Aprobar liquidaciones de sucursales', false),
('chofer', 'settlements.client.view', 'Ver Liquidaciones Cliente', 'Consultar liquidaciones de clientes', false),
('chofer', 'commissions.view', 'Ver Mis Comisiones', 'Consultar comisiones propias', true),
('chofer', 'clients.view', 'Ver Clientes', 'Consultar lista de clientes', false),
('chofer', 'clients.manage', 'Gestionar Clientes', 'Administrar clientes', false),
('chofer', 'branches.manage', 'Gestionar Sucursales', 'Administrar sucursales', false),
('chofer', 'rates.manage', 'Gestionar Tarifas', 'Configurar precios y tarifas', false),
('chofer', 'users.manage', 'Gestionar Usuarios', 'Administrar usuarios del sistema', false),
('chofer', 'roles.manage', 'Gestionar Roles', 'Configurar permisos por rol', false);

-- DESPACHADOR
INSERT INTO public.role_permissions (role, permission_key, permission_name, description, enabled) VALUES
('despachador', 'dashboard.view', 'Ver Dashboard', 'Acceso al panel de control principal', true),
('despachador', 'shipments.view', 'Ver Envíos', 'Consultar lista de envíos', true),
('despachador', 'shipments.create', 'Crear Envíos', 'Registrar nuevos envíos', true),
('despachador', 'shipments.edit', 'Editar Envíos', 'Modificar datos de envíos', true),
('despachador', 'shipments.scan', 'Escanear QR', 'Escanear códigos QR de envíos', true),
('despachador', 'tracking.view', 'Ver Tracking', 'Consultar estado de envíos públicamente', true),
('despachador', 'routes.plan', 'Planificar Rutas', 'Usar el planificador de rutas', false),
('despachador', 'route_sheets.view', 'Ver Hojas de Ruta', 'Consultar hojas de ruta', true),
('despachador', 'route_sheets.create', 'Crear Hojas de Ruta', 'Generar nuevas hojas de ruta', true),
('despachador', 'live_map.view', 'Ver Mapa en Vivo', 'Monitorear ubicación de choferes', false),
('despachador', 'drivers.manage', 'Gestionar Choferes', 'Administrar choferes del sistema', false),
('despachador', 'vehicles.manage', 'Gestionar Vehículos', 'Administrar flota de vehículos', false),
('despachador', 'my_routes.view', 'Ver Mis Rutas', 'Ver rutas asignadas personalmente', false),
('despachador', 'route.start', 'Iniciar Ruta', 'Comenzar una ruta de entrega', false),
('despachador', 'navigation.active', 'Navegación Activa', 'Usar navegación GPS en ruta', false),
('despachador', 'delivery.confirm', 'Confirmar Entregas', 'Registrar entregas con foto/firma', false),
('despachador', 'incidents.report', 'Reportar Incidentes', 'Registrar problemas durante entrega', false),
('despachador', 'cash.manage', 'Gestionar Caja', 'Manejar sesiones de caja', false),
('despachador', 'settlements.driver.view', 'Ver Liquidaciones Chofer', 'Consultar liquidaciones de choferes', false),
('despachador', 'settlements.driver.manage', 'Gestionar Liquidaciones Chofer', 'Aprobar/pagar liquidaciones de choferes', false),
('despachador', 'settlements.branch.view', 'Ver Liquidaciones Sucursal', 'Consultar liquidaciones de sucursales', false),
('despachador', 'settlements.branch.manage', 'Gestionar Liquidaciones Sucursal', 'Aprobar liquidaciones de sucursales', false),
('despachador', 'settlements.client.view', 'Ver Liquidaciones Cliente', 'Consultar liquidaciones de clientes', false),
('despachador', 'commissions.view', 'Ver Mis Comisiones', 'Consultar comisiones propias', false),
('despachador', 'clients.view', 'Ver Clientes', 'Consultar lista de clientes', true),
('despachador', 'clients.manage', 'Gestionar Clientes', 'Administrar clientes', false),
('despachador', 'branches.manage', 'Gestionar Sucursales', 'Administrar sucursales', false),
('despachador', 'rates.manage', 'Gestionar Tarifas', 'Configurar precios y tarifas', false),
('despachador', 'users.manage', 'Gestionar Usuarios', 'Administrar usuarios del sistema', false),
('despachador', 'roles.manage', 'Gestionar Roles', 'Configurar permisos por rol', false);

-- BODEGA
INSERT INTO public.role_permissions (role, permission_key, permission_name, description, enabled) VALUES
('bodega', 'dashboard.view', 'Ver Dashboard', 'Acceso al panel de control principal', true),
('bodega', 'shipments.view', 'Ver Envíos', 'Consultar lista de envíos', true),
('bodega', 'shipments.create', 'Crear Envíos', 'Registrar nuevos envíos', false),
('bodega', 'shipments.edit', 'Editar Envíos', 'Modificar datos de envíos', true),
('bodega', 'shipments.scan', 'Escanear QR', 'Escanear códigos QR de envíos', true),
('bodega', 'tracking.view', 'Ver Tracking', 'Consultar estado de envíos públicamente', true),
('bodega', 'routes.plan', 'Planificar Rutas', 'Usar el planificador de rutas', false),
('bodega', 'route_sheets.view', 'Ver Hojas de Ruta', 'Consultar hojas de ruta', true),
('bodega', 'route_sheets.create', 'Crear Hojas de Ruta', 'Generar nuevas hojas de ruta', false),
('bodega', 'live_map.view', 'Ver Mapa en Vivo', 'Monitorear ubicación de choferes', false),
('bodega', 'drivers.manage', 'Gestionar Choferes', 'Administrar choferes del sistema', false),
('bodega', 'vehicles.manage', 'Gestionar Vehículos', 'Administrar flota de vehículos', false),
('bodega', 'my_routes.view', 'Ver Mis Rutas', 'Ver rutas asignadas personalmente', false),
('bodega', 'route.start', 'Iniciar Ruta', 'Comenzar una ruta de entrega', false),
('bodega', 'navigation.active', 'Navegación Activa', 'Usar navegación GPS en ruta', false),
('bodega', 'delivery.confirm', 'Confirmar Entregas', 'Registrar entregas con foto/firma', false),
('bodega', 'incidents.report', 'Reportar Incidentes', 'Registrar problemas durante entrega', false),
('bodega', 'cash.manage', 'Gestionar Caja', 'Manejar sesiones de caja', false),
('bodega', 'settlements.driver.view', 'Ver Liquidaciones Chofer', 'Consultar liquidaciones de choferes', false),
('bodega', 'settlements.driver.manage', 'Gestionar Liquidaciones Chofer', 'Aprobar/pagar liquidaciones de choferes', false),
('bodega', 'settlements.branch.view', 'Ver Liquidaciones Sucursal', 'Consultar liquidaciones de sucursales', false),
('bodega', 'settlements.branch.manage', 'Gestionar Liquidaciones Sucursal', 'Aprobar liquidaciones de sucursales', false),
('bodega', 'settlements.client.view', 'Ver Liquidaciones Cliente', 'Consultar liquidaciones de clientes', false),
('bodega', 'commissions.view', 'Ver Mis Comisiones', 'Consultar comisiones propias', false),
('bodega', 'clients.view', 'Ver Clientes', 'Consultar lista de clientes', false),
('bodega', 'clients.manage', 'Gestionar Clientes', 'Administrar clientes', false),
('bodega', 'branches.manage', 'Gestionar Sucursales', 'Administrar sucursales', false),
('bodega', 'rates.manage', 'Gestionar Tarifas', 'Configurar precios y tarifas', false),
('bodega', 'users.manage', 'Gestionar Usuarios', 'Administrar usuarios del sistema', false),
('bodega', 'roles.manage', 'Gestionar Roles', 'Configurar permisos por rol', false);

-- ATENCION_CLIENTE
INSERT INTO public.role_permissions (role, permission_key, permission_name, description, enabled) VALUES
('atencion_cliente', 'dashboard.view', 'Ver Dashboard', 'Acceso al panel de control principal', true),
('atencion_cliente', 'shipments.view', 'Ver Envíos', 'Consultar lista de envíos', true),
('atencion_cliente', 'shipments.create', 'Crear Envíos', 'Registrar nuevos envíos', true),
('atencion_cliente', 'shipments.edit', 'Editar Envíos', 'Modificar datos de envíos', false),
('atencion_cliente', 'shipments.scan', 'Escanear QR', 'Escanear códigos QR de envíos', false),
('atencion_cliente', 'tracking.view', 'Ver Tracking', 'Consultar estado de envíos públicamente', true),
('atencion_cliente', 'routes.plan', 'Planificar Rutas', 'Usar el planificador de rutas', false),
('atencion_cliente', 'route_sheets.view', 'Ver Hojas de Ruta', 'Consultar hojas de ruta', false),
('atencion_cliente', 'route_sheets.create', 'Crear Hojas de Ruta', 'Generar nuevas hojas de ruta', false),
('atencion_cliente', 'live_map.view', 'Ver Mapa en Vivo', 'Monitorear ubicación de choferes', false),
('atencion_cliente', 'drivers.manage', 'Gestionar Choferes', 'Administrar choferes del sistema', false),
('atencion_cliente', 'vehicles.manage', 'Gestionar Vehículos', 'Administrar flota de vehículos', false),
('atencion_cliente', 'my_routes.view', 'Ver Mis Rutas', 'Ver rutas asignadas personalmente', false),
('atencion_cliente', 'route.start', 'Iniciar Ruta', 'Comenzar una ruta de entrega', false),
('atencion_cliente', 'navigation.active', 'Navegación Activa', 'Usar navegación GPS en ruta', false),
('atencion_cliente', 'delivery.confirm', 'Confirmar Entregas', 'Registrar entregas con foto/firma', false),
('atencion_cliente', 'incidents.report', 'Reportar Incidentes', 'Registrar problemas durante entrega', false),
('atencion_cliente', 'cash.manage', 'Gestionar Caja', 'Manejar sesiones de caja', false),
('atencion_cliente', 'settlements.driver.view', 'Ver Liquidaciones Chofer', 'Consultar liquidaciones de choferes', false),
('atencion_cliente', 'settlements.driver.manage', 'Gestionar Liquidaciones Chofer', 'Aprobar/pagar liquidaciones de choferes', false),
('atencion_cliente', 'settlements.branch.view', 'Ver Liquidaciones Sucursal', 'Consultar liquidaciones de sucursales', false),
('atencion_cliente', 'settlements.branch.manage', 'Gestionar Liquidaciones Sucursal', 'Aprobar liquidaciones de sucursales', false),
('atencion_cliente', 'settlements.client.view', 'Ver Liquidaciones Cliente', 'Consultar liquidaciones de clientes', true),
('atencion_cliente', 'commissions.view', 'Ver Mis Comisiones', 'Consultar comisiones propias', false),
('atencion_cliente', 'clients.view', 'Ver Clientes', 'Consultar lista de clientes', true),
('atencion_cliente', 'clients.manage', 'Gestionar Clientes', 'Administrar clientes', true),
('atencion_cliente', 'branches.manage', 'Gestionar Sucursales', 'Administrar sucursales', false),
('atencion_cliente', 'rates.manage', 'Gestionar Tarifas', 'Configurar precios y tarifas', false),
('atencion_cliente', 'users.manage', 'Gestionar Usuarios', 'Administrar usuarios del sistema', false),
('atencion_cliente', 'roles.manage', 'Gestionar Roles', 'Configurar permisos por rol', false);

-- SUCURSAL
INSERT INTO public.role_permissions (role, permission_key, permission_name, description, enabled) VALUES
('sucursal', 'dashboard.view', 'Ver Dashboard', 'Acceso al panel de control principal', true),
('sucursal', 'shipments.view', 'Ver Envíos', 'Consultar lista de envíos', true),
('sucursal', 'shipments.create', 'Crear Envíos', 'Registrar nuevos envíos', true),
('sucursal', 'shipments.edit', 'Editar Envíos', 'Modificar datos de envíos', true),
('sucursal', 'shipments.scan', 'Escanear QR', 'Escanear códigos QR de envíos', true),
('sucursal', 'tracking.view', 'Ver Tracking', 'Consultar estado de envíos públicamente', true),
('sucursal', 'routes.plan', 'Planificar Rutas', 'Usar el planificador de rutas', false),
('sucursal', 'route_sheets.view', 'Ver Hojas de Ruta', 'Consultar hojas de ruta', true),
('sucursal', 'route_sheets.create', 'Crear Hojas de Ruta', 'Generar nuevas hojas de ruta', false),
('sucursal', 'live_map.view', 'Ver Mapa en Vivo', 'Monitorear ubicación de choferes', false),
('sucursal', 'drivers.manage', 'Gestionar Choferes', 'Administrar choferes del sistema', false),
('sucursal', 'vehicles.manage', 'Gestionar Vehículos', 'Administrar flota de vehículos', false),
('sucursal', 'my_routes.view', 'Ver Mis Rutas', 'Ver rutas asignadas personalmente', false),
('sucursal', 'route.start', 'Iniciar Ruta', 'Comenzar una ruta de entrega', false),
('sucursal', 'navigation.active', 'Navegación Activa', 'Usar navegación GPS en ruta', false),
('sucursal', 'delivery.confirm', 'Confirmar Entregas', 'Registrar entregas con foto/firma', false),
('sucursal', 'incidents.report', 'Reportar Incidentes', 'Registrar problemas durante entrega', false),
('sucursal', 'cash.manage', 'Gestionar Caja', 'Manejar sesiones de caja', true),
('sucursal', 'settlements.driver.view', 'Ver Liquidaciones Chofer', 'Consultar liquidaciones de choferes', false),
('sucursal', 'settlements.driver.manage', 'Gestionar Liquidaciones Chofer', 'Aprobar/pagar liquidaciones de choferes', false),
('sucursal', 'settlements.branch.view', 'Ver Liquidaciones Sucursal', 'Consultar liquidaciones de sucursales', true),
('sucursal', 'settlements.branch.manage', 'Gestionar Liquidaciones Sucursal', 'Aprobar liquidaciones de sucursales', false),
('sucursal', 'settlements.client.view', 'Ver Liquidaciones Cliente', 'Consultar liquidaciones de clientes', false),
('sucursal', 'commissions.view', 'Ver Mis Comisiones', 'Consultar comisiones propias', false),
('sucursal', 'clients.view', 'Ver Clientes', 'Consultar lista de clientes', true),
('sucursal', 'clients.manage', 'Gestionar Clientes', 'Administrar clientes', true),
('sucursal', 'branches.manage', 'Gestionar Sucursales', 'Administrar sucursales', false),
('sucursal', 'rates.manage', 'Gestionar Tarifas', 'Configurar precios y tarifas', false),
('sucursal', 'users.manage', 'Gestionar Usuarios', 'Administrar usuarios del sistema', false),
('sucursal', 'roles.manage', 'Gestionar Roles', 'Configurar permisos por rol', false);

-- CLIENTE
INSERT INTO public.role_permissions (role, permission_key, permission_name, description, enabled) VALUES
('cliente', 'dashboard.view', 'Ver Dashboard', 'Acceso al panel de control principal', false),
('cliente', 'shipments.view', 'Ver Envíos', 'Consultar lista de envíos', true),
('cliente', 'shipments.create', 'Crear Envíos', 'Registrar nuevos envíos', true),
('cliente', 'shipments.edit', 'Editar Envíos', 'Modificar datos de envíos', false),
('cliente', 'shipments.scan', 'Escanear QR', 'Escanear códigos QR de envíos', false),
('cliente', 'tracking.view', 'Ver Tracking', 'Consultar estado de envíos públicamente', true),
('cliente', 'routes.plan', 'Planificar Rutas', 'Usar el planificador de rutas', false),
('cliente', 'route_sheets.view', 'Ver Hojas de Ruta', 'Consultar hojas de ruta', false),
('cliente', 'route_sheets.create', 'Crear Hojas de Ruta', 'Generar nuevas hojas de ruta', false),
('cliente', 'live_map.view', 'Ver Mapa en Vivo', 'Monitorear ubicación de choferes', false),
('cliente', 'drivers.manage', 'Gestionar Choferes', 'Administrar choferes del sistema', false),
('cliente', 'vehicles.manage', 'Gestionar Vehículos', 'Administrar flota de vehículos', false),
('cliente', 'my_routes.view', 'Ver Mis Rutas', 'Ver rutas asignadas personalmente', false),
('cliente', 'route.start', 'Iniciar Ruta', 'Comenzar una ruta de entrega', false),
('cliente', 'navigation.active', 'Navegación Activa', 'Usar navegación GPS en ruta', false),
('cliente', 'delivery.confirm', 'Confirmar Entregas', 'Registrar entregas con foto/firma', false),
('cliente', 'incidents.report', 'Reportar Incidentes', 'Registrar problemas durante entrega', false),
('cliente', 'cash.manage', 'Gestionar Caja', 'Manejar sesiones de caja', false),
('cliente', 'settlements.driver.view', 'Ver Liquidaciones Chofer', 'Consultar liquidaciones de choferes', false),
('cliente', 'settlements.driver.manage', 'Gestionar Liquidaciones Chofer', 'Aprobar/pagar liquidaciones de choferes', false),
('cliente', 'settlements.branch.view', 'Ver Liquidaciones Sucursal', 'Consultar liquidaciones de sucursales', false),
('cliente', 'settlements.branch.manage', 'Gestionar Liquidaciones Sucursal', 'Aprobar liquidaciones de sucursales', false),
('cliente', 'settlements.client.view', 'Ver Liquidaciones Cliente', 'Consultar liquidaciones de clientes', true),
('cliente', 'commissions.view', 'Ver Mis Comisiones', 'Consultar comisiones propias', false),
('cliente', 'clients.view', 'Ver Clientes', 'Consultar lista de clientes', false),
('cliente', 'clients.manage', 'Gestionar Clientes', 'Administrar clientes', false),
('cliente', 'branches.manage', 'Gestionar Sucursales', 'Administrar sucursales', false),
('cliente', 'rates.manage', 'Gestionar Tarifas', 'Configurar precios y tarifas', false),
('cliente', 'users.manage', 'Gestionar Usuarios', 'Administrar usuarios del sistema', false),
('cliente', 'roles.manage', 'Gestionar Roles', 'Configurar permisos por rol', false);